In [1]:
#1
import numpy as np

In [2]:
#2
zero_array = np.zeros(10)
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#3
zer_array = np.zeros(10)
zer_array[4] = 1
print(zer_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
#4
rng_array = np.arange(10,49)
print(rng_array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [14]:
#5
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
#6

y = np.array([1,2,0,0,4,0])

np.nonzero(y)


(array([0, 1, 4]),)

In [17]:
#7

z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
#8 

t = np.random.random((3,3,3))
print(t)

[[[0.65399578 0.29975406 0.33100302]
  [0.78789207 0.18765219 0.23599572]
  [0.58906077 0.84550691 0.68809972]]

 [[0.66279378 0.32314323 0.99642739]
  [0.04089889 0.16874597 0.14807337]
  [0.70276045 0.6298902  0.02668437]]

 [[0.10361901 0.37917501 0.80655908]
  [0.31252744 0.91934493 0.02167113]
  [0.63474463 0.73985876 0.22570708]]]


In [25]:
#9


a = np.random.random((10,10))
np.amax(a)

0.9886506771276775

In [26]:
#9

a = np.random.random((10,10))
np.amin(a)


0.005367346870010725

In [28]:
#10

b = np.random.random(30)
print(np.mean(b))

0.5618015341421334


In [29]:
#11 

mtrx = np.diag([1, 2, 3, 4], k=-1)
mtrx

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [31]:
#12

m = np.random.random((5,5))

mean_m = np.mean(m)

std_m = np.std(m)

normalized = (m - mean_m) / std_m 

print(m)
print(mean_m)
print(std_m)
print(normalized)

[[0.82033923 0.24638683 0.92623913 0.61815851 0.02831468]
 [0.3524351  0.05033682 0.4886237  0.12129261 0.22857756]
 [0.2451715  0.35313224 0.9340621  0.16875468 0.46707294]
 [0.63003897 0.91456511 0.98321066 0.45178602 0.83406672]
 [0.95140636 0.74743017 0.14944853 0.95479543 0.21033066]]
0.5150390504712228
0.3237988447543807
[[ 0.94286987 -0.82968863  1.26992447  0.31846765 -1.50316895]
 [-0.50217583 -1.43515717 -0.0815795  -1.21602177 -0.88468967]
 [-0.83344198 -0.50002282  1.29408444 -1.06944288 -0.14813552]
 [ 0.35515854  1.23387118  1.44587178 -0.19534668  0.98526501]
 [ 1.34764937  0.71770214 -1.12906678  1.35811595 -0.94104225]]


In [33]:
#13


xy = np.array([2,3,6,8,9])
yx = np.array([2,3,5,7,8])

intersc = np.intersect1d(xy,yx)
print(intersc)

[2 3 8]


In [34]:
#14 

yz = np.random.random(10)
print(np.sort(yz))

[0.0866763  0.13421096 0.2025452  0.23983536 0.75565078 0.78914217
 0.79573334 0.88013826 0.88542942 0.96130971]


In [40]:
#15

zt = np.random.random(10)
zt[zt.argmax()] = 0

print(zt)

[0.3317655  0.81564145 0.         0.40708513 0.57306663 0.50958493
 0.87143818 0.55962783 0.39209746 0.66567468]


In [41]:
#16

sw = np.random.random((3, 3))
print(sw)

qw = sw - sw.mean(axis=1, keepdims=True) #keepdims is a bit unclear, check it later, found it online
print(qw)


[[0.14193578 0.74699027 0.4095435 ]
 [0.81869439 0.33532472 0.80174462]
 [0.1816744  0.2557712  0.23994983]]
[[-0.2908874   0.31416708 -0.02327969]
 [ 0.16677315 -0.31659652  0.14982337]
 [-0.04412408  0.02997273  0.01415135]]


In [42]:
#17 

ab = np.arange(10000)
np.random.shuffle(ab)

print(ab)

args_ab = np.argsort(ab)  #this argsort is for index of sorted array

srt_ab = ab[args_ab] 

n = 5

largest = srt_ab[-n : ]

print(largest)


[ 940 1552 1400 ... 8148 8119 6294]
[9995 9996 9997 9998 9999]


In [43]:
#18

n = np.random.random((5,3))

np.where(n>4)

print(n**2)

[[9.77189950e-01 7.30104755e-01 8.91678870e-01]
 [9.59551216e-02 8.08502378e-02 4.96891703e-01]
 [3.97966097e-04 7.54991060e-01 6.74047686e-01]
 [9.26485841e-02 1.60764207e-01 1.88736172e-01]
 [9.86803669e-04 1.90179290e-01 3.47693213e-01]]
